# Generated by Django 3.0.6 on 2020-05-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='contractor',
            name='city',
            field=models.ManyToManyField(to='handy.City'),
        ),
    ]
