# Generated by Django 3.0.6 on 2020-06-07 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0002_auto_20200521_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handy.City')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handy.Contractor')),
            ],
        ),
        migrations.AlterField(
            model_name='contractor',
            name='city',
            field=models.ManyToManyField(through='handy.Location', to='handy.City'),
        ),
    ]
