# Generated by Django 3.0.6 on 2020-06-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0002_contractor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
