# Generated by Django 3.0.6 on 2020-06-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0003_auto_20200625_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
