# Generated by Django 3.0.6 on 2020-06-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0003_auto_20200606_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='city',
            field=models.ManyToManyField(to='handy.City'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
